version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - .:/opt/repo
    ports:
    - 9090:9090
    environment:
      TARO_ENV: dev
  # postgres:
  #   image: "postgres"
