version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - ./config.yaml:/opt/repo/config.yaml
    - ./.htpasswd:/opt/repo/.htpasswd
    - ./ffmpeg.log:/opt/repo/ffmpeg.log
    - ./mount/frags:/opt/mount/frags
    ports:
    - 80:80
    - 443:443
    - 1935:1935
    environment:
      TARO_ENV: prd
    links:
    - postgres:taro-db
    depends_on:
    - 'postgres'
  postgres:
    image: "postgres"
