version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - .:/opt/repo
    - ./mount/frags:/opt/mount/frags
    ports:
    - 9090:80
    - 1935:1935
    environment:
      TARO_ENV: dev
    links:
    - postgres:taro-db
    depends_on:
    - 'postgres'
  postgres:
    image: "postgres"
