version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - .:/opt/repo
    - ./mount/frags:/opt/mount/frags
    ports:
    - 9090:80
    environment:
      TARO_ENV: dev
    links:
    - postgres:taro-db
    depends_on:
    - 'postgres'
    restart: always
  watcher:
    build:
      context: .
      dockerfile: ./watcher/Dockerfile
    volumes:
    - .:/opt/repo
    - ./mount/frags:/opt/mount/frags
    links:
    - postgres:taro-db
    depends_on:
    - 'web'
    restart: always
  srs:
    build:
      context: .
      dockerfile: ./srs/Dockerfile
    volumes:
    - .:/opt/repo
    - ./mount/frags:/opt/mount/frags
    ports:
    - 1935:1935
    restart: always
    links:
    - web:web
  postgres:
    image: "postgres"
    volumes:
    - ./mount/db:/var/lib/postgresql/data
