version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - ./mount/frags:/opt/mount/frags
    ports:
    - 80:80
    - 443:443
    - 1935:1935
    environment:
      TARO_ENV: prd
  # postgres:
  #   image: "postgres"
