version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - ./config.yaml:/opt/repo/config.yaml
    - ./gsa.json:/opt/repo/gsa.json
    - ./.htpasswd:/opt/repo/.htpasswd
    - ./mount/frags:/opt/mount/frags
    - ./mount/getssl-web/.well-known/:/opt/www/.well-known/
    - ./mount/getssl-cert/:/opt/ssl/
    expose:
    - '80'
    - '443'
    environment:
      TARO_ENV: prd
    links:
    - postgres:taro-db
    depends_on:
    - 'postgres'
    restart: always
    network_mode: bridge
  watcher:
    build:
      context: .
      dockerfile: ./watcher/Dockerfile
    volumes:
    - ./config.yaml:/opt/repo/config.yaml
    - ./mount/frags:/opt/mount/frags
    links:
    - postgres:taro-db
    depends_on:
    - 'web'
    restart: always
    network_mode: bridge
  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    volumes:
    - ./config.yaml:/opt/repo/config.yaml
    links:
    - postgres:taro-db
    depends_on:
    - 'web'
    network_mode: bridge
  srs:
    build:
      context: .
      dockerfile: ./srs/Dockerfile
    volumes:
    - ./mount/frags:/opt/mount/frags
    ports:
    - 1935:1935
    restart: always
    links:
    - web:web
    network_mode: bridge
  postgres:
    image: "postgres"
    volumes:
    - ./mount/db:/var/lib/postgresql/data
    network_mode: bridge
