version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - .:/opt/repo
    - ./mount/frags:/opt/mount/frags
    ports:
    - 9090:80
    environment:
      TARO_ENV: dev
    links:
    - postgres:taro-db
    depends_on:
    - 'postgres'
    restart: always
  rtmp:
    build:
      context: .
      dockerfile: ./web/rtmp.Dockerfile
    volumes:
    - .:/opt/repo
    - ./web/nginx/rtmp.conf:/etc/nginx/nginx.conf
    - ./mount/frags:/opt/mount/frags
    ports:
    - 1935:1935
    restart: always
  postgres:
    image: "postgres"
    volumes:
    - ./mount/db:/var/lib/postgresql/data
