version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
    - ./config.yaml:/opt/repo/config.yaml
    - ./gsa.json:/opt/repo/gsa.json
    - ./.htpasswd:/opt/repo/.htpasswd
    - ./mount/frags:/opt/mount/frags
    ports:
    - 80:80
    - 443:443
    environment:
      TARO_ENV: prd
    links:
    - postgres:taro-db
    depends_on:
    - 'postgres'
    restart: always
  srs:
    build:
      context: .
      dockerfile: ./srs/Dockerfile
    volumes:
    - ./mount/frags:/opt/mount/frags
    ports:
    - 1935:1935
    restart: always
    links:
    - web:web
  postgres:
    image: "postgres"
    volumes:
    - ./mount/db:/var/lib/postgresql/data
